#+TITLE: tog-cli

[[tag][file:https://img.shields.io/github/v/tag/Vernacular-ai/tog-cli.svg]] [[https://cheeseshop.vernacular.ai/tog][https://cheeseshop.vernacular.ai/--badger--/tog.svg]]

Command line interface for interacting with tog data server. Available on
internal cheeseshop and can be installed via:

#+begin_src shell
pip install tog --extra-index-url https://cheeseshop.vernacular.ai
#+end_src

Tog data server is our store of tagged/untagged data. Tagging efforts are
organized in terms of =jobs= which keep a bunch of =tasks= to be tagged.

As of now we only support downloading of data from a certain job in this tool.
Further development will add more visibility in the stored data, feature to
upload data etc.

** Configuration
For almost all commands you will need credentials to be set in a few environment
variables for the backend. An example follows. You can contact a team member to
get the credentials for our server.

#+begin_src shell
export TOGDB_HOST=localhost
export TOGDB_PORT=9999
export TOGDB_USER=username
export TOGDB_PASS=password
#+end_src

** Usage
For downloading a job data, you first need to know the integer id of that job
and its task type. Then run something like the following:

#+begin_src shell
  tog download --job-id=61 --output-sqlite=job-61.sqlite --task-type audio_segment
#+end_src

Task type is optional and only needed if you want to do type validation. If you
don't provide it, we just assume raw dictionary objects. Nevertheless, look in
=./tog/types.py= for description of various task types. The string identifiers
to be used in cli can be found in =tog.db.build_task= function.

For more usage details, try =tog --help=.
